version: '3.8'

services:
  redis:
    image: redis:6.0

  nginx:
    build:
      context: ./nginx
    volumes:
      - "./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./nginx/src:/usr/local/src"
    depends_on:
      - redis
    ports:
      - "80:80"
